algorithm:
  match_score: 1.0
  mismatch_score: -1.5
  open_gap_score: -1.0
  extend_gap_score: -1.0
  min_score: 20.0
  max_iterations: 100

seeding:
  k: 50
  max_gap: 50
  extend: 50
  max_kmer_hits: 5

preprocessing:
  strip_chars: "\\_"

input:
  dir: "input"

output:
  path: "output/results.csv"