algorithm:
  match_score: 1.0
  mismatch_score: -1.5
  open_gap_score: -1.0
  extend_gap_score: -1.0
  min_score: 30.0
  max_iterations: 100

seeding:
  k: 30
  max_gap: 100
  extend: 250
  max_kmer_hits: 5

preprocessing:
  strip_chars: "\\_"

input:
  # dir: "test_data/test_data5_rebecca"
  dir: "test_data/test_data7_sonam"

output:
  # path: "test_data/test_data5_rebecca"
  path: "output/test_data7_sonam.csv"